### ISSUE TITLE
mongodb store추가

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/midgard#2]

**Comment by zeroFruit** [comment]
@junbeomlee 
진행시작해보겠습니다

**Comment by zeroFruit** [comment]
@junbeomlee 
현재 leveldb에서 쓰이는 serializer가 mongodb에서도 쓰일 거 같은데 serializer 부분을 /store에 util.go로 따로 빼는건 어떤가요?

**Comment by junbeomlee** [comment]
좋네요!! 
util.go 보다는 event_serializer.go or serializer라는 이름이 더 명확하게 무슨 기능을 포함하는지 짐작할 수 있을 것 같습니다!

**Comment by junbeomlee** [comment]
close하겠습니다
